### ISSUE TITLE
new VueRouter() ... "Argument is not assignable to parameter of type 'RouterOptions'."

### ISSUE THREAD

**Issue by beanstalkblue** [bradyholt/koa-vuejs-template#2]
After a fresh git clone of koa-vuejs-template, in /client-web/boot.ts VSCode complains "Argument is not assignable to parameter of type 'RouterOptions'."

<img width="783" alt="screen shot 2017-10-28 at 1 34 25 pm" src="https://user-images.githubusercontent.com/26293523/32136930-30edb15a-bbe5-11e7-88ef-985deea96b0a.png">

The code still compiles and runs fine. How can I remove these linter warnings?

**Comment by bradyholt** [comment]
Strange, I don't know offhand.  Mind taking a crack at figuring it out?

**Comment by beanstalkblue** [comment]
Remove "typeof" from vue.d.ts file to avoid this issue in latest Typescript.

New vue.d.ts:

```
declare module "*.vue" {
  import Vue from "vue";
  export default Vue;
}
```
